version: '3'
services:
  node:
    container_name: planningpoker-app
    image: 'node:12.9-alpine'
    restart: always
    user: 'node'
    working_dir: /home/node/app
    environment:
      - NODE_ENV=${NODE_ENV:-production}
    volumes:
      - ./:/home/node/app
    ports:
      - 80:8080
      - 1235:1235
    command: 'npm run serve:${NODE_ENV:-production}'
